pizza_wac/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^', include('pizzas.urls')),
    url(r'^admin/', admin.site.urls,name='admin_view'),
]

pizzas/urls.py
from django.conf.urls import url

from . import views

app_name = 'pizza'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    #Panier
    url(r'^add$', views.ajoutPanier, name='addPanier'),
    url(r'^remove$', views.removePanier, name='removePanier'),
    url(r'^panier$', views.panier, name='panier'),
    url(r'^boisson$', views.BoissonView.as_view(), name='boisson'),
]

pizzas/models.py
from django.db import models


class Pizza(models.Model):
    name = models.CharField(max_length=200)
    desc = models.TextField(default="Loremp Ipsum")
    prix = models.FloatField(default=0)
    type = models.CharField(default="pizzas",max_length=20)

    def __str__(self):
        return self.name


class ingredient(models.Model):
    pizzas = models.ManyToManyField(Pizza)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Boisson(models.Model):
    name = models.CharField(max_length=200)
    prix = models.FloatField(default=0)
    type = models.CharField(default="boissons",max_length=20)

    def __str__(self):
        return self.name


class Entree(models.Model):
    name = models.CharField(max_length=200)
    prix = models.FloatField(default=0)
    type = models.CharField(default="entrees",max_length=20)


    def __str__(self):
        return self.name


class Menu(models.Model):
    name = models.CharField(max_length=200)
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    entree = models.ForeignKey(Entree, on_delete=models.CASCADE)
    boisson = models.ForeignKey(Boisson, on_delete=models.CASCADE)
    prix = models.FloatField(default=0)
    type = models.CharField(default="menus",max_length=20)


    def __str__(self):
        return self.name

pizzas/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from .models import Pizza, ingredient, Menu, Boisson, Entree
from django.utils import timezone
from django.template import RequestContext
from django.core.urlresolvers import reverse


def index(request):
    all_boisson = Boisson.objects.order_by('-name')[:3]
    all_entrees = Entree.objects.order_by('-name')[:3]
    all_menu = Menu.objects.order_by('-name')[:3]
    alls_pizza = Pizza.objects.order_by('-name')[:6]
    return render(request, 'pizzas/index.html', {'all_pizza': alls_pizza, 'all_boisson': all_boisson, 'all_menu': all_menu})


class DetailView(generic.DetailView):
    model = Pizza
    template_name = 'pizzas/detail.html'


def ajoutPanier(request):
    if request.method == 'POST':
        if request.POST['type'] == "pizza":
            if not request.session.get('pizza_id'):
                request.session['pizza_id'] = []
            pizza_id = request.POST['pizza_id']
            pizza_list = request.session['pizza_id']
            pizza_list = pizza_list + [pizza_id]
            request.session['pizza_id'] = pizza_list

        elif request.POST['type'] == "boisson":
            if not request.session.get('boisson_id'):
                request.session['boisson_id'] = []
            boisson_id = request.POST['boisson_id']
            boisson_list = request.session['boisson_id']
            boisson_list = boisson_list + [boisson_id]
            request.session['boisson_id'] = boisson_list

        elif request.POST['type'] == "menu":
            if not request.session.get('menu_id'):
                request.session['menu_id'] = []
            menu_id = request.POST['menu_id']
            menu_list = request.session['menu_id']
            menu_list = menu_list + [menu_id]
            request.session['menu_id'] = menu_list

        elif request.POST['type'] == "entree":
            if not request.session.get('entree_id'):
                request.session['entree_id'] = []
            entree_id = request.POST['entree_id']
            entree_list = request.session['entree_id']
            entree_list = entree_list + [entree_id]
            request.session['entree_id'] = entree_list
        return HttpResponseRedirect(reverse('pizza:panier'))

    else:
        request.session.flush()
        return HttpResponseRedirect(reverse('pizza:index'))


def panier(request):
    total_ttc = 0;

    if not request.session.get('pizza_id'):
        request.session['pizza_id'] = []
    if not request.session.get('boisson_id'):
        request.session['boisson_id'] = []

    pizza_obj = []
    boisson_obj = []
    menu_obj = []

    for pizza_id in request.session['pizza_id']:
        thisPizza = Pizza.objects.get(id=pizza_id)
        total_ttc += thisPizza.prix
        pizza_obj = pizza_obj + [thisPizza]

    for boisson_id in request.session['boisson_id']:
        thisboisson = Boisson.objects.get(id=boisson_id)
        total_ttc += thisboisson.prix
        boisson_obj = boisson_obj + [thisboisson]

    for menu_id in request.session['menu_id']:
        thismenu = Menu.objects.get(id=menu_id)
        total_ttc += thismenu.prix
        menu_obj = menu_obj + [thismenu]

    pizza_obj = pizza_obj + boisson_obj + menu_obj
    return render(request, 'pizzas/panier.html',
                  {'pizza_commander': pizza_obj, 'total_ttc': total_ttc})


def removePanier(request):
    pizza_id = request.POST['pizza_id']
    index_remove = request.session['pizza_id'].index(pizza_id)
    del request.session['pizza_id'][index_remove]
    # return HttpResponse(request.session['pizza_id'])
    return HttpResponseRedirect(reverse('pizza:panier'))


class BoissonView(generic.ListView):
    template_name = 'pizzas/boisson.html'
    context_object_name = 'all_boisson'

    def get_queryset(self):
        """Return the last five published questions."""
        return

pizzas/templates/pizzas/boisson.html
{% extends "pizzas/global.html" %}
{% load staticfiles %}
{% block content %}
    <div class="jumbotron">
        <h1>My Pizza, Le meilleur de la pizza!</h1>
        <p>Une pizza achetée une offerte pour les pizzas à emporter. -15 % ce soir sur les livraisons </p>
    </div>
    {% if all_pizza %}
        <div class="allPizza">
            {% for pizza in all_pizza %}
                <div class="col-md-4">
                    <div class="onePizza">
                        <a class="name" href="{% url 'pizza:detail' pizza.id %}">{{ pizza.name }}</a>
                        <p class="desc col-md-8">{{ pizza.desc|truncatewords_html:25 }}</p>
                        <img class="col-md-4" src="{% static 'pizzas/images/' %}{{ pizza.id }}.png" alt="">
                        <div class="more row">
                            <div class="col-md-6 btn-group" role="group">
                                <form action="{% url 'pizza:addPanier' %}" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" value="{{ pizza.id }}" name="pizza_id">
                                    <button type="submit" href="#" class="btn btn-success btn-xs">Commander</button>
                                </form>
                            </div>
                            <div class="col-md-6">
                                <p class="prix text-right">{{ pizza.pizza_prix }} €</p>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>Aucune pizza de disponible</p>
    {% endif %}
{% endblock %}

pizzas/templates/pizzas/detail.html
{% extends "pizzas/global.html" %}
{% load staticfiles %}
{% block content %}
    <div class="jumbotron">
        <h1 class="text-center">La {{ pizza.name }}</h1>
        <div class="col-md-9"><p>{{ pizza.desc }}</p></div>
        <div class="col-md-3"><img style="max-width: 200px;" src="{% static 'pizzas/images/' %}{{ pizza.type }}/{{ pizza.id }}.png"></div>
        <a href="#" class="btn btn-primary">Ajoutez au panier</a>
        <div class="clearfix"></div>
    </div>
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h2 class="panel-title">CKOI2Dans :</h2>
        </div>
        <div class="panel-body">
            <ul>
                {% for ingredient in pizza.ingredient_set.all %}
                    <li>{{ ingredient }}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

pizzas/templates/pizzas/global.html
<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>My Pizza</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'pizzas/css/style.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'pizzas/css/bootstrap.min.css' %}"/>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url "pizza:index" %}">My Pyzza.fr</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="#">Pizzas <span class="sr-only">(current)</span></a></li>
                <li><a href="#">Entrées</a></li>
                <li><a href="#">Boissons</a></li>
                <li><a href="#">Nos Menus</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'pizza:panier' %}">Mon panier</a></li>
                {% if user.is_authenticated %}
                    <li class="dropdown">

                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">Mon compte <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="/admin">Admin</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                        </ul>
                    </li>
                 {% else %}
                    <li><a href="/admin">Me connecter</a></li>
                {% endif %}

            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<div class="container">
    {% block content %}{% endblock %}
</div>

<script src="{% static 'pizzas/js/jquery.min.js' %}"></script>
<script src="{% static 'pizzas/js/bootstrap.min.js' %}"></script>
<script src="{% static 'pizzas/js/script.js' %}"></script>
</body>
</html>

pizzas/templates/pizzas/index.html
{% extends "pizzas/global.html" %}
{% load staticfiles %}
{% block content %}
    <div class="jumbotron">
        <h1>My Pizza, Le meilleur de la pizza!</h1>
        <p>Une pizza achetée une offerte pour les pizzas à emporter. -15 % ce soir sur les livraisons </p>
    </div>
    {% if all_menu %}
        <section class="allPizza">
            <div class="row">
                <header><h2 class="text-capitalize">Nos boissons:</h2></header>
            </div>
            {% for menu in all_menu %}
                <div class="col-md-4">
                    <div class="onePizza">
                        <a class="name" href="#">{{ menu.name }}</a>
                        <div>
                           <ul style="margin-top: 15px;">
                               <li>{{ menu.entree }}</li>
                               <li>{{ menu.pizza }}</li>
                               <li>{{ menu.boisson }}</li>
                           </ul>
                        </div>
                        <div class="more row">
                            <br>
                            <div class="col-md-6 btn-group" role="group">
                                <form action="{% url 'pizza:addPanier' %}" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" value="{{ menu.id }}" name="menu_id">
                                    <input type="hidden" value="menu" name="type">
                                    <button type="submit" href="#" class="btn btn-success btn-xs">Commander</button>
                                </form>
                            </div>
                            <div class="col-md-6">
                                <p class="prix text-right">{{ menu.prix }} €</p>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </section>
    {% else %}
        <p>Aucune entrée de disponible</p>
    {% endif %}{#  If end entree#}


    {# Pizza #}
    {% if all_pizza %}
        <section class="allPizza">
            <div class="row">
                <header><h2 class="text-capitalize">Les pizzas:</h2></header>
            </div>
            {% for pizza in all_pizza %}
                <div class="col-md-4">
                    <div class="onePizza">
                        <a class="name" href="{% url 'pizza:detail' pizza.id %}">{{ pizza.name }}</a>
                        <p class="desc col-md-8">{{ pizza.desc|truncatewords_html:25 }}</p>
                        <img class="col-md-4" src="{% static 'pizzas/images/' %}{{ pizza.type }}/{{ pizza.id }}.png"
                             alt="boissons">
                        <div class="more row">
                            <div class="col-md-6 btn-group" role="group">
                                <form action="{% url 'pizza:addPanier' %}" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" value="{{ pizza.id }}" name="pizza_id">
                                    <input type="hidden" value="pizza" name="type">
                                    <button type="submit" href="#" class="btn btn-success btn-xs">Commander</button>
                                </form>
                            </div>
                            <div class="col-md-6">
                                <p class="prix text-right">{{ pizza.prix }} €</p>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            {% endfor %}
        </section>
    {% else %}
        <p>Aucune pizza de disponible</p>
    {% endif %}{#  If end pizza#}


    {# BOISSON #}
    {% if all_boisson %}
        <section class="allPizza">
            <div class="row">
                <header><h2 class="text-capitalize">Nos boissons:</h2></header>
            </div>
            {% for boisson in all_boisson %}
                <div class="col-md-4">
                    <div class="onePizza">
                        <a class="name" href="#">{{ boisson.name }}</a>
                        <div class="col-md-4 col-md-offset-4">
                            <img src="{% static 'pizzas/images/boissons/' %}{{ boisson.id }}.png"
                                 alt="boisson" style="height: 100px; margin: 10px 0">
                        </div>
                        <div class="more row">
                            <br>
                            <div class="col-md-6 btn-group" role="group">
                                <form action="{% url 'pizza:addPanier' %}" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" value="{{ boisson.id }}" name="boisson_id">
                                    <input type="hidden" value="boisson" name="type">
                                    <button type="submit" href="#" class="btn btn-success btn-xs">Commander</button>
                                </form>
                            </div>
                            <div class="col-md-6">
                                <p class="prix text-right">{{ boisson.prix }} €</p>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            {% endfor %}
        </section>
    {% else %}
        <p>Aucune boisson de disponible</p>
    {% endif %}
{% endblock %}

pizzas/templates/pizzas/panier.html
{% extends 'pizzas/global.html' %}
{% load staticfiles %}

{% block content %}
    <div class="panel panel-primary" id="start">
        <div class="panel-heading">
            <h1 class="panel-title">Votre commande</h1>
        </div>
        <div class="panel-body">
            {% if pizza_commander %}
                <p class="titre">{{ pizza_commander|length }} produit(s) : {{ total_ttc|floatformat:2 }} €</p>
                <div class="allPizza row">
                    {% for pizza in pizza_commander %}
                        <div class="col-md-4">
                            <div class="onePizza">
                                <a class="name" href="{% url 'pizza:detail' pizza.id %}">{{ pizza.name }}</a>

                                {% if pizza.type == "pizzas" %}
                                    <p class="desc col-md-8">{{ pizza.desc|truncatewords_html:25 }}</p>
                                    <img class="col-md-4"
                                         src="{% static 'pizzas/images/' %}{{ pizza.type }}/{{ pizza.id }}.png"
                                         alt="Photo d un sublime Pizza !">
                                {% elif pizza.type == "menus" %}
                                    <div>
                                        <ul style="margin-top: 15px;">
                                            <li>{{ pizza.entree }}</li>
                                            <li>{{ pizza.pizza }}</li>
                                            <li>{{ pizza.boisson }}</li>
                                        </ul>
                                    </div>
                                {% elif pizza.type == "boissons" %}
                                    <div class="col-md-4 col-md-offset-4">
                                        <img src="{% static 'pizzas/images/boissons/' %}{{ pizza.id }}.png"
                                             alt="boisson" style="height: 100px; margin: 10px 0">
                                    </div>
                                {% endif %}

                                <div class="more row">
                                    <div class="col-md-6">
                                        <form action="{% url 'pizza:removePanier' %}" method="post">
                                            {% csrf_token %}
                                            <input type="hidden" value="{{ pizza.id }}" name="pizza_id">
                                            <button type="submit" href="#" class="btn btn-danger btn-xs">Supprimer
                                            </button>
                                        </form>
                                    </div>
                                    <div class="col-md-6">
                                        <p class="prix text-right">{{ pizza.prix }} €</p>
                                    </div>
                                </div>

                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="row">
                    <p>&nbsp;</p>
                    <p class="text-center"><a href="{% url 'pizza:index' %}" class="btn btn-info">Continuer mes
                        achats</a></p>
                    <p class="text-center"><a href="{% url 'pizza:index' %}" id="lunchReglement"
                                              class="btn btn-success">Valider et payer ma
                        commande de {{ total_ttc|floatformat:2 }} €</a></p>
                </div>
            {% else %}
                <p class="alert alert-info">Vous n'avez aucune pizza en commande</p>
                <p class="text-center"><a href="{% url 'pizza:index' %}" class="btn btn-info">Commander un produit</a>
                </p>
            {% endif %}
        </div>
    </div>

    <div class="panel panel-primary" id="reglement">
        <div class="panel-heading">
            <h2 class="panel-title">Réglement</h2>
        </div>
        <div class="panel-body">

            <div id="coordone" style="margin-top: 20px;">
                <h3 class="panel-title" style="margin: 15px 0;color: #008CBA">Vos coordonées</h3>
                <form action="#" class="form-group">
                    <input placeholder="Prénom" class="form-control" type="text" name="prenom" id="prenom"><br>
                    <input placeholder="Nom de famille" class="form-control" type="text" name="nomFamille"
                           id="nomFamille"><br>
                    <input placeholder="Adresse" class="form-control" type="text" name="adresse" id="adresse"><br>
                    <input placeholder="Code Postal" class="form-control" type="number" name="codePostal"
                           id="codePostal"><br>
                    <input placeholder="Ville" class="form-control" type="text" name="ville" id="ville"><br>
                    <input placeholder="Numeros de téléphone" class="form-control" type="tel" name="telephone"
                           id="telephone"><br>
                </form>
            </div>
            <div id="methode">
                <h3 class="panel-title" style="margin-bottom: 15px;color: #008CBA">Méthode de paiement</h3>
                <div class="col-md-4">
                    <input type="checkbox" name="tr" id="tr">
                    &nbsp;<label for="tr">Ticket restaurant</label>
                </div>
                <div class="col-md-4">
                    <input type="checkbox" name="espece" id="espece">
                    &nbsp;<label for="espece">Espèce</label>
                </div>
                <div class="col-md-4">
                    <input type="checkbox" name="cb" id="cb">
                    &nbsp;<label for="cb">Carte Bancaire</label>
                </div>
                <div class="clearfix"></div>
                <br>
                <div class="text-center"><a href="#" class="btn btn-success" id="validateCommande">Validé</a></div>
            </div>
        </div>
    </div>
    <div class="panel panel-primary" id="resume">
        <div class="panel-heading">
            <h3 class="panel-title">Votre commande est validée</h3>
        </div>
        <div class="panel-body">
            <h4>Merci <span id="resumePrenon"></span></h4>
            <p>&nbsp;</p>
            <p>La livraison de votre commande sera livré aux <br>
                <strong id="resumeAdresse"></strong></p>

            <p>Votre Pizzeria preferé</p>
            <br><br>
            <a href="{% url 'pizza:addPanier' %}" class="btn btn-primary">Recommencer</a>
        </div>
    </div>

{% endblock %}
<div id="methode">